version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=email_engine
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app
    command: npm start

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: